### ISSUE TITLE
How can I check vinli device disconnected ?

### ISSUE THREAD

**Issue by tsurutan** [vinli/android-bt#12]
I use ```POWER_STATUS``` and ```CONNECTION_STATUS``` as param, but I can't check vinli device disconnected.

**Comment by cmc5788** [comment]
Disconnects are a natural part of the BLE life cycle and we will automatically try to reconnect indefinitely until you unsubscribe all from all observables on the device connection. It's up to the user to implement logic for a timeout after which they consider the device disconnected, such as after some amount of time without receiving valid data.

**Comment by tsurutan** [comment]
Thank you for your reply.
OK, I'll implement logic for a timeout.
