### ISSUE TITLE
Calling VinliDevices.connect() disconnects other BT devices

### ISSUE THREAD

**Issue by Kahtaf** [vinli/android-bt#13]
Calling VinliDevices.connect() disconnects an already connected bluetooth device when attempting to connect to the Vinli device. 

I noticed this issue when I'm already connected to my car's bluetooth and playing music, launching an app which calls VinliDevices.connect() will disconnect my car's bluetooth (and stop music playback). 

Is there a way to restore the previous connection? I know it's possible to have both connections active because I can reconnect to my car's bluetooth and play music after connecting to my Vinli device.

**Comment by cmc5788** [comment]
@Kahtaf I'll take a look. Right now we have logic that will reset the Bluetooth adapter when GATT errors are encountered during the connection process, which on some devices and manufacturers, is on almost every connection attempt - Android support for BLE is not fantastic. Maybe we can overload the connect method to prefer Vinli connection failure over BLE stack reset.

**Comment by cmc5788** [comment]
Closing since this was related to service provided by My Vinli, not the bt SDK, and is fixed now regardless
